config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  devise_scope :admin do
    authenticated :admin do
      root 'users#index', as: :authenticated_root
      get '/admins/sign_out' => 'devise/sessions#destroy'
    end

    unauthenticated do
        root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users
  resources :minimum_transactions
  resources :rewards

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        collection do
          post :signup
          post :login
          get :logout
          get :user_details
          post :update_user
          post :confirm_user
          post :resend_otp
          post :password_forget
          post :password_reset
          post :update_password
          post :social_login
          post :rewards_claim
          get :rewards_history
        end
      end
      resources :coins do
        collection do
          post :all_coin_details
          post :coin_details
        end
      end
      resources :rewards do
        collection do
          post :all_rewards
        end
      end
      resources :leaderboards, only:[:index] do
      end
      resources :user_transactions do
        collection do
          post :coin_transaction
          get :transaction_detail
          post :coin_transaction_detail
        end
      end
    end
  end
end

app/models/reward.rb
class Reward < ApplicationRecord
  has_many :rewards
  mount_uploader :company_logo, BrandLogoUploader
end

app/controllers/api/v1/rewards_controller.rb
class Api::V1::RewardsController < ApiApplicationController

  before_action :check_if_current_api_user

  def all_rewards
    @current_date = params[:current_date]
    @reward_list = @current_user.user_rewards.pluck("reward_id")
    if @reward_list.present?
      @rewards = Reward.where("expiry >= ?", @current_date).where("id NOT IN (?)",@reward_list).order("expiry")
    else
      @rewards = Reward.where("expiry >= ?", @current_date).order("expiry")
    end
    if @rewards.present?
      render json: { status: true, data: @rewards, message: 'Rewards history' }, status: 200
    else
      render json: { status: false, message: "No rewards available." }, status: 404
    end
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController

  def index
    @rewards = Reward.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @reward = Reward.new
  end

  def create
    @reward = Reward.new(reward_params.merge(reward_status: 'true'))
    if @reward.save
      redirect_to rewards_url, notice: 'Reward was successfully created.'
    else
      render :new
    end
  end

  def edit
    @reward = Reward.find(params[:id])
  end

  def update
    @reward = Reward.find(params[:id])
    if @reward.update(reward_params)
      redirect_to rewards_url, notice: 'Reward was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy
    redirect_to rewards_url, notice: 'Reward destroyed successfully.'
  end

  private

  def reward_params
    params.require(:reward).permit(:company_name, :company_logo, :reward_image_url, :offer, :expiry, :description, :reward_code, :reward_status, :price)
  end
end

app/helpers/api/v1/rewards_helper.rb
module Api::V1::RewardsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= form_for :reward, url: rewards_path, method: :post do |form| %>
<%= form.hidden_field :updated_by, value: 'admin' %>
  <% if @reward.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(reward.errors.count, "error") %> prohibited this reward from being saved:</h3>

      <ul>
      <% reward.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name, id: :company_name  %>
  </div>

  <div class="field">
    <%= form.label :company_logo %>
    <%= form.file_field :company_logo, id: :company_logo %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :price %>
  </div>

  <div class="field">
    <%= form.label :offer %>
    <%= form.text_field :offer, id: :offer %>
  </div>

  <div class="field">
    <%= form.label :expiry %>
    <%= form.date_select :expiry, id: :expiry %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :description %>
  </div>

  <div class="field">
    <%= form.label :reward_code %>
    <%= form.text_field :reward_code, id: :reward_code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rewards/edit.html.erb
<div class='container'>
	<h1>Editing Reward</h1>

	<div class='container'>
  <%= form_for @reward, method: :patch do |form| %>
		<div class="field">
	    <%= form.label :company_name %>
	    <%= form.text_field :company_name, id: :company_name  %>
	  </div>

	  <div class="field">
	    <%= form.label :company_logo %>
	    <%= form.file_field :company_logo, id: :company_logo %>
	  </div>

	  <div class="field">
	    <%= form.label :price %>
	    <%= form.text_field :price, id: :price %>
	  </div>

	  <div class="field">
	    <%= form.label :offer %>
	    <%= form.text_field :offer, id: :offer %>
	  </div>

		<div class="field">
			<%= form.label :expiry %>
			<%= form.date_select :expiry, id: :expiry %>
		</div>

		<div class="field">
			<%= form.label :description %>
			<%= form.text_field :description, id: :description %>
		</div>

		<div class="field">
			<%= form.label :reward_code %>
			<%= form.text_field :reward_code, id: :reward_code %>
		</div>

    <p>
      <%= link_to 'Back', rewards_path, class:"btn btn-info btn-sm" %>
      <%= form.submit "Save", class:"btn btn-info btn-sm" %>
    </p>
  <% end %>
</div>


</div>

app/views/rewards/index.html.erb
<h1>Rewards Management</h1>
<table class='table table-bordered'>
  <thead>
    <tr>
      <th>Sr.No.</th>
      <th>Company Name</th>
      <th>Price</th>
      <th>Offer</th>
      <th>Expiry</th>
      <th>Description</th>
      <th>Reward Code</th>
      <th>Reward Status</th>
      <th>Brand Logo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rewards.each_with_index do |reward, index| %>
      <tr>
        <td><%= index+1 %></td>
        <td><%= reward.company_name %></td>
        <td><%= reward.price %></td>
        <td><%= reward.offer %></td>
        <td><%= reward.expiry %></td>
        <td><%= reward.description %></td>
        <td><%= reward.reward_code %></td>
        <td><%= reward.reward_status %></td>
        <td><%= image_tag reward.company_logo.url(:thumb) unless reward.company_logo.url.blank? %></td>
        <td><%= button_to 'Edit', edit_reward_path(reward), :method => "get", class: 'btn btn-info btn-sm'%></td>
        <td><%= button_to 'Delete', reward_path(reward), method: :delete, class: 'btn btn-info btn-sm', data: { confirm: 'Are you sure, you want to delete the user?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @rewards %>
    </div>
    <%= will_paginate @rewards, :container => false %>
  </div>
<br>

<%= link_to 'Add Reward', new_reward_path %>
<!-- style:'width:100%;' -->

app/views/rewards/new.html.erb
<h1>New Reward</h1>

<%= form_for @reward, url: rewards_path, method: :post do |form| %>
<%= form.hidden_field :updated_by, value: 'admin' %>
  <% if @reward.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(reward.errors.count, "error") %> prohibited this reward from being saved:</h3>

      <ul>
      <% reward.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name, id: :company_name, :required => true  %>
  </div>

  <div class="field">
    <%= form.label :company_logo %>
    <%= form.file_field :company_logo, id: :company_logo %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :price, :required => true %>
  </div>

  <div class="field">
    <%= form.label :offer %>
    <%= form.text_field :offer, id: :offer, :required => true %>
  </div>

  <div class="field">
    <%= form.label :expiry %>
    <%= form.date_select :expiry, id: :expiry, :required => true %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :description, :required => true %>
  </div>

  <div class="field">
    <%= form.label :reward_code %>
    <%= form.text_field :reward_code, id: :reward_code, :required => true %>
  </div>

  <div class="actions">
    <%= form.submit %>
    <%= button_to 'Back', rewards_path %>
  </div>
<% end %>