config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  devise_scope :admin do
    authenticated :admin do
      root 'users#index', as: :authenticated_root
      get '/admins/sign_out' => 'devise/sessions#destroy'
    end

    unauthenticated do
        root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users
  resources :minimum_transactions
  resources :rewards

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        collection do
          post :signup
          post :login
          get :logout
          get :user_details
          post :update_user
          post :confirm_user
          post :resend_otp
          post :password_forget
          post :password_reset
          post :update_password
          post :social_login
          post :rewards_claim
          get :rewards_history
        end
      end
      resources :coins do
        collection do
          post :all_coin_details
          post :coin_details
        end
      end
      resources :rewards do
        collection do
          post :all_rewards
        end
      end
      resources :leaderboards, only:[:index] do
      end
      resources :user_transactions do
        collection do
          post :coin_transaction
          get :transaction_detail
          post :coin_transaction_detail
        end
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :user
end

app/models/leader_board.rb
class LeaderBoard < ApplicationRecord
  belongs_to :user

  def user_worth
    @users = User.where(active: 'true').pluck(:id)
    @users.each do |user|
      coins_worth = coin_amount_calculation(user).to_f
      rewards_worth = rewards_worth_calculation(user).to_f
      master_wallet_worth = master_wallet(user)
      net_worth = rewards_worth + coins_worth + master_wallet_worth
      growth_rate = delta_growth(user).to_f
      which_user = LeaderBoard.where(user_id: user).last
      worth = which_user.update_attributes!(user_id: user, net_worth: net_worth,
                                             growth_rate: growth_rate)
    end
  end

  def coin_amount_calculation(user)
    coin_amount = 0
    coins = UserCoin.where(user_id: user)
    coins.each do |coin|
      coin_name = coin.coin_name
      coin_data = Cryptocompare::Price.find('USD', coin_name)
      coin_value = coin_data['USD'][coin_name]
      coin_amount = coin_amount + coin_value
    end
    return coin_amount
  end

  def rewards_worth_calculation(user)
    reward_worth = 0
    rewards = UserReward.where(user_id: user)
    rewards.each do |reward|
      reward_value = Reward.find_by_id(reward.reward_id).price.to_i
      reward_worth = reward_worth + reward_value
    end
    return reward_worth
  end

  def master_wallet(user)
    master_wallet = MasterWallet.where(user_id: user).last
    master_wallet_worth = 0.to_f
    if master_wallet.present?
      master_wallet_worth = master_wallet.try(:amount)
    end
    return master_wallet_worth
  end

  def delta_growth(user)
    previous_worth = LeaderBoard.where(user_id: user).last.net_worth.to_f
    current_worth = rewards_worth_calculation(user).to_f
    delta_growth = (((previous_worth - current_worth)/previous_worth).to_f)*100
    return delta_growth
  end
end

app/models/master_wallet.rb
class MasterWallet < ApplicationRecord
  belongs_to :user
end

app/models/minimum_transaction.rb
class MinimumTransaction < ApplicationRecord
end

app/models/reward.rb
class Reward < ApplicationRecord
  has_many :rewards
  mount_uploader :company_logo, BrandLogoUploader
end

app/models/user.rb
class User < ApplicationRecord

  has_one :device, dependent: :destroy
  has_one :master_wallet, dependent: :destroy
  has_many :user_transaction, dependent: :destroy
  has_many :user_coins, dependent: :destroy
  has_many :rewards, dependent: :destroy
  has_many :user_rewards, dependent: :destroy

  mount_uploader :profile_image, ProfileImageUploader

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: {maximum: 75}
  validates :phone, presence: true, numericality: {only_integer: true}, length: {maximum: 10, minimum: 10}, uniqueness: true
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def self.generate_token
    SecureRandom.urlsafe_base64
  end

  def create_reset_digest
    reset_token = SecureRandom.hex(3)
    update_attribute(:reset_digest, reset_token)
    update_attribute(:reset_sent_at, Time.zone.now)
  end
end

app/models/user_coin.rb
class UserCoin < ApplicationRecord
  belongs_to :user_transaction
  belongs_to :user
end

app/models/user_reward.rb
class UserReward < ApplicationRecord
  belongs_to :user
  belongs_to :reward
end

app/models/user_transaction.rb
class UserTransaction < ApplicationRecord
  belongs_to :user
  has_many :user_coin

  validates :amount, presence: true
  validates :transaction_type, presence: true
end

app/controllers/api_application_controller.rb
class ApiApplicationController < ActionController::API

  def unauthorized_json
  {
    status: "false",
    message: "Access denied"
  }
  end
 
  private

  def check_if_device_present
    unless device_present
      render json: unauthorized_json, status: :unauthorized, code: 401
    end
  end

  def device_present
    @@device_id = request.headers['DeviceId']
    @@device_type = request.headers['DeviceType']
    return true if @@device_id && @@device_type
  end

  def check_if_current_api_user
    unless current_api_user
      render json: {status: false, message: 'Auth not available or already logout.' }, status: 401
    end
  end

  def current_api_user
    return @current_user if @current_user
    if auth_token = request.headers['Authorization']
      @current_user = User.where(auth_token: auth_token).first
    end
  end

  def render_not_found
    render json: { error: 'Record not found' }, status: 404, head: :not_found
  end

  def render_ok
    render json: { message: 'ok' }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_admin!
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController

  def index
    @rewards = Reward.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @reward = Reward.new
  end

  def create
    @reward = Reward.new(reward_params.merge(reward_status: 'true'))
    if @reward.save
      redirect_to rewards_url, notice: 'Reward was successfully created.'
    else
      render :new
    end
  end

  def edit
    @reward = Reward.find(params[:id])
  end

  def update
    @reward = Reward.find(params[:id])
    if @reward.update(reward_params)
      redirect_to rewards_url, notice: 'Reward was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy
    redirect_to rewards_url, notice: 'Reward destroyed successfully.'
  end

  private

  def reward_params
    params.require(:reward).permit(:company_name, :company_logo, :reward_image_url, :offer, :expiry, :description, :reward_code, :reward_status, :price)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:destroy]

  def index
    @users = User.paginate(:page => params[:page], :per_page => 10)
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/minimum_transactions_helper.rb
module MinimumTransactionsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cryptox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if admin_signed_in? %>
        <%= render 'shared/nav_bar' %>
      <% else %>
        <%= yield %>
      <% end %>
  </body>
</html>

app/views/shared/_nav_bar.html.erb
<div class="wrapper" style="overflow: hidden; height: auto;">
	<!-- Header -->
	<header class="main-header">
		<!-- Logo -->
		<!-- <a href="#" class="sidebar-toggle hidden-lg hidden-md hidden-sm" data-toggle="offcanvas" role="button">
			<span class="sr-only">Toggle navigation</span>
		</a> -->
		<a href="#" class="logo">
			<!-- mini logo for sidebar mini 50x50 pixels -->
			<span class="logo-mini hide">

			</span>
			<!-- logo for regular state and mobile devices -->
			<span class="logo-lg">
				<%= image_tag 'logo_header.png', class: "img-responsive center-block" %>

			</span>
		</a>
		<!-- Header Navbar: style can be found in header.less -->
		<nav class="navbar navbar-static-top">
			<!-- Sidebar toggle button-->
			<a href="#" class="sidebar-toggle hide" data-toggle="offcanvas" role="button">
				<span class="sr-only">Toggle navigation</span>
			</a>
		</nav>
	</header>
	<!-- Header -->
	<aside class="main-sidebar">
		<section class="sidebar" style="height: auto;">
			<!-- Sidebar user panel -->
			<div class="user-panel">
				<div class="pull-left image">
					<%= image_tag 'profile.jpg', class: "img-circle", alt: "User Image" %>
				</div>
				<div class="pull-left info">
					<p>Admin</p>
					<a href="#"><i class="fa fa-circle text-success"></i> Online</a>
				</div>
			</div>
			<!-- sidebar menu: : style can be found in sidebar.less -->
			<ul class="sidebar-menu">

				<li class="">
					<%= link_to "<i class='fa fa-user'></i> User Management".html_safe, users_path %>
				</li>
				<li class="">
					<%= link_to "<i class='fa fa-pencil-square-o'></i> Minimum Transaction".html_safe, minimum_transactions_path %>
				</li>
				<li class="">
					<%= link_to "<i class='fa fa-barcode'></i> Rewards Management".html_safe, rewards_path %>
				</li>
				<li>
					<%= link_to "<i class='fa fa-sign-out'></i> Sign out".html_safe, destroy_admin_session_path, method: :delete %>
				</li>
				</ul>
			</section>
		</aside>
		<div class="content-wrapper" style="min-height: 428px;">

            <section class="content">
                <div class="box box-default">
			<%= alert %>
			<%= notice %>
			<%= yield %>
		</div>
	</section>
		</div>
		<!-- Footer -->
		<footer class="main-footer">
			Copyright © 2017 <a href="#!">Mobikasa Pvt Ltd</a>. All rights reserved.
		</footer>
		<!-- Footer -->
	</div>